(()=>{
const id=Number(document.body.dataset.dictee),d=window.DICTEES.find(x=>x.id===id),app=document.querySelector('#app');
if(!d){app.innerHTML='<p>Dictée introuvable.</p>';return}
const key='zm-d'+id,colors=['yellow','green','violet'];
let lvl=0,mode='flash',queue=[],index=0,points=0,answer='',reviewAnswer='',timer;
const baseWord=w=>w.replace(/^(un|une|le|la|les|des|l[’'])\s*/i,'').replace(/\s/g,''),reverse=w=>[...baseWord(w)].reverse().join('');
const clean=s=>s.trim().replace(/[’']/g,"'").normalize('NFC'),norm=s=>clean(s).toLowerCase();
const same=(value,expected)=>/[A-ZÀ-ÖØ-Þ]/.test(expected)?clean(value)===clean(expected):norm(value)===norm(expected);
const pool=()=>d.levels.slice(0,lvl+1).flat(),pick=(a,n)=>[...a].sort(()=>Math.random()-.5).slice(0,Math.min(n,a.length));
const repair=a=>{const m=new Map(d.levels.flat().map(w=>[reverse(w),baseWord(w)]));return [...new Set(a.map(w=>m.get(w)||w))]};
const hard=w=>{const a=repair(JSON.parse(localStorage.getItem(key)||'[]'));if(!a.includes(w))a.push(w);localStorage.setItem(key,JSON.stringify(a))};
const speak=w=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w);u.lang='fr-FR';u.rate=.72;speechSynthesis.speak(u)};

app.innerHTML=`<header class="dict-hero"><div><span class="tag">DICTÉE ${id} · CM2</span><h1>${d.title}</h1><p>Cinq missions courtes pour observer, mémoriser, transformer et écrire.</p></div><div class="dict-nav"><a ${id>1?`href="${fileFor(id-1)}"`:''}>←</a><span>${id} / 25</span><a ${id<25?`href="${fileFor(id+1)}"`:''}>→</a></div></header>
<section class="dict-wrap"><figure class="artwork"><div class="art-frame"><img id="art" alt="Illustration en lien avec ${d.title}"><span id="artFallback">ŒUVRE<br>À OBSERVER</span></div><figcaption><b>Observe l’œuvre avant de commencer.</b><br>Que remarques-tu ? Quels détails sont liés au thème de la dictée ?<small id="credit">Illustration recherchée dans Wikimedia Commons.</small></figcaption></figure>
<section class="levels">${colors.map((c,n)=>`<button class="level ${c} ${n===0?'active':''}" data-l="${n}">${c.toUpperCase()}<small>${n===0?'Mots essentiels':n===1?'Jaune + intermédiaires':'Toute la liste'}</small></button>`).join('')}</section>
<div class="status"><span class="pill" id="levelName">Niveau jaune</span><span class="pill" id="score">0 réussite</span><div class="progress"><span id="progressFill"></span></div></div>
<section class="missions"><button class="mission active" data-m="flash">👁️<b>Mot éclair</b><span>Observer puis écrire</span></button><button class="mission" data-m="transform">🔄<b>Je transforme</b><span>Accords et formes</span></button><button class="mission" data-m="choice">🎯<b>Je choisis</b><span>Reconnaître l’orthographe</span></button><button class="mission" data-m="dictation">🎧<b>Mini-dictée</b><span>Écouter puis écrire</span></button><button class="mission" data-m="reverse">↩️<b>Bonus à l’envers</b><span>De la fin au début</span></button><button class="study-tab" id="study">📚<b>Revoir les mots</b><span>Liste du niveau</span></button><button class="study-tab" id="review">⭐<b>Mes mots à revoir</b><span>Mes erreurs</span></button></section>
<section class="game" id="game"></section></section>`;

const game=document.querySelector('#game');
function fileFor(n){const names=['grottes','megalithes','ecriture','artisanat-gaulois','monuments-gallo-romains','seigneurs','paysans','eglises','guillaume-conquerant','alienor-aquitaine','inventions','exploration','renaissance','guerres-religion','monarchie-absolue','revolution-francaise','napoleon','revolution-industrielle','expansion-coloniale','progres-sociaux','premiere-guerre','seconde-guerre','resistance','societe-consommation','futur'];return `dictee-${String(n).padStart(2,'0')}-${names[n-1]}.html`}
function updateStatus(){document.querySelector('#score').textContent=points+' réussite'+(points>1?'s':'');document.querySelector('#progressFill').style.width=(queue.length?Math.min(100,index/queue.length*100):0)+'%'}
function inputForm(title,prompt,expected,audio=false,review=expected){answer=expected;reviewAnswer=review;game.innerHTML=`<h2>${title}</h2><p class="prompt">${prompt}</p>${audio?'<button class="action audio" id="hear">🔊 ÉCOUTER LE MOT</button>':''}<label class="write-label" for="inp">✏️ CLIQUE ICI ET ÉCRIS TA RÉPONSE</label><textarea class="answer-input" id="inp" rows="1" inputmode="text" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="Écris ta réponse ici…"></textarea><button class="action" id="check">VALIDER</button><div class="feedback" id="feed"></div>`;if(audio)document.querySelector('#hear').onclick=()=>speak(expected);const inp=document.querySelector('#inp');document.querySelector('#check').onclick=check;inp.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check()}};inp.focus()}
function check(){const inp=document.querySelector('#inp'),f=document.querySelector('#feed');if(same(inp.value,answer)){points++;f.className='feedback ok';f.textContent='✓ Bravo !'}else{hard(reviewAnswer||answer);f.className='feedback bad';f.textContent='La réponse était : '+answer}updateStatus();setTimeout(next,950)}
function start(){clearTimeout(timer);index=points=0;if(mode==='transform'){const available=d.transforms.filter(x=>x[2]<=lvl);queue=pick(available.length?available:d.transforms,4)}else queue=pick(pool(),mode==='dictation'?(lvl===0?5:lvl===1?7:9):mode==='choice'?5:4);updateStatus();next()}
function next(){if(index>=queue.length)return finish();updateStatus();if(mode==='flash'){const w=queue[index++];game.innerHTML=`<h2>MOT ÉCLAIR · ${index}/${queue.length}</h2><p class="flash-word">${w}</p><p class="hint">Observe bien le mot…</p>`;timer=setTimeout(()=>inputForm(`MOT ÉCLAIR · ${index}/${queue.length}`,'Le mot a disparu.',w),3200);return}if(mode==='transform'){const x=queue[index++];inputForm(`JE TRANSFORME · ${index}/${queue.length}`,x[0],x[1]);return}if(mode==='dictation'){const w=queue[index++];inputForm(`MINI-DICTÉE · ${index}/${queue.length}`,'Écoute le mot.',w,true);return}if(mode==='reverse'){const w=queue[index++],original=baseWord(w);inputForm(`BONUS À L’ENVERS · ${index}/${queue.length}`,'Écoute le mot puis écris-le de la dernière lettre à la première.',reverse(w),false,original);game.querySelector('.prompt').insertAdjacentHTML('afterend','<button class="action audio" id="hear">🔊 ÉCOUTER LE MOT</button><p class="hint">Le mot ne sera pas affiché.</p>');document.querySelector('#hear').onclick=()=>speak(original);return}const w=queue[index++],bad1=w.replace(/[éèêàâîôûç]/i,'e'),bad2=w.endsWith('s')?w.slice(0,-1):w+'s',opts=[w,bad1,bad2].filter((x,n,a)=>a.indexOf(x)===n).sort(()=>Math.random()-.5);game.innerHTML=`<h2>JE CHOISIS · ${index}/${queue.length}</h2><p class="prompt">Quelle est la bonne orthographe ?</p><div class="choices">${opts.map(x=>`<button>${x}</button>`).join('')}</div>`;game.querySelectorAll('.choices button').forEach(b=>b.onclick=()=>{if(same(b.textContent,w))points++;else hard(w);updateStatus();setTimeout(next,600)})}
function finish(){updateStatus();document.querySelector('#progressFill').style.width='100%';game.innerHTML=`<h2>MISSION TERMINÉE</h2><p class="result">${points} / ${queue.length}</p><p>${points===queue.length?'Mission parfaite !':'Les erreurs sont conservées dans « Mes mots à revoir ».'}</p><button class="action" id="again">REJOUER</button>`;document.querySelector('#again').onclick=start}
function wordsMarkup(words){return words.map(w=>`<span class="word">${w}</span>`).join('')}
function showWords(){clearTimeout(timer);deactivate();document.querySelector('#study').classList.add('active');game.innerHTML=`<h2>REVOIR LES MOTS · ${colors[lvl].toUpperCase()}</h2><p class="hint">Lis et mémorise les mots. Ils disparaîtront dès le début d’un exercice.</p><div class="words">${wordsMarkup(pool())}</div>`}
function showReview(){clearTimeout(timer);deactivate();document.querySelector('#review').classList.add('active');const a=repair(JSON.parse(localStorage.getItem(key)||'[]'));localStorage.setItem(key,JSON.stringify(a));if(!a.length){game.innerHTML='<h2>MES MOTS À REVOIR</h2><p class="prompt">Aucun mot difficile enregistré.</p><p class="hint">Les erreurs apparaîtront ici automatiquement.</p>';return}game.innerHTML=`<h2>MES MOTS À REVOIR</h2><p class="hint">Tous les mots sont présentés à l’endroit.</p><div class="words">${wordsMarkup(a)}</div><button class="action" id="practice">M’ENTRAÎNER SUR CES MOTS</button>`;document.querySelector('#practice').onclick=()=>{deactivate();mode='dictation';queue=a;index=points=0;next()}}
function deactivate(){document.querySelectorAll('.mission,.study-tab').forEach(x=>x.classList.remove('active'))}
document.querySelectorAll('.level').forEach(b=>b.onclick=()=>{document.querySelectorAll('.level').forEach(x=>x.classList.remove('active'));b.classList.add('active');lvl=Number(b.dataset.l);document.querySelector('#levelName').textContent='Niveau '+colors[lvl];document.querySelector('#study').classList.contains('active')?showWords():document.querySelector('#review').classList.contains('active')?showReview():start()});
document.querySelectorAll('.mission').forEach(b=>b.onclick=()=>{deactivate();b.classList.add('active');mode=b.dataset.m;start()});document.querySelector('#study').onclick=showWords;document.querySelector('#review').onclick=showReview;
async function artwork(){try{const url='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=6&gsrsearch='+encodeURIComponent(d.query)+'&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=1200&format=json&origin=*';const j=await fetch(url).then(r=>r.json()),pages=Object.values(j.query?.pages||{}),p=pages.find(x=>x.imageinfo?.[0]?.thumburl);if(!p)return;const info=p.imageinfo[0],img=document.querySelector('#art');img.src=info.thumburl;img.onload=()=>document.querySelector('#artFallback').hidden=true;document.querySelector('#credit').textContent='Illustration : Wikimedia Commons · '+(p.title||'') }catch(e){}}
artwork();start();
})();
