'use strict';
const $=id=>document.getElementById(id);
const modes=[['🔊','Listen & Find','Écoute et retrouve la bonne image.'],['👀','Image → Word','Associe une image au mot anglais.'],['🧠',"What’s Missing?",'Mémorise les images : laquelle a disparu ?'],['🔗','Match','Associe quatre sons à leurs images.'],['🔤','Spelling','Construis les mots avec les lettres.'],['🎒','Look & answer','Observe les cartes et réponds.'],['🧩','Build the sentence','Remets les mots de la phrase en ordre.'],['💬','English in action','Comprends les expressions de la leçon.'],['⚡','Fast Challenge','Trouve la réponse en huit secondes.'],['🏆','Final Mission','Combine écoute, mémoire et orthographe.']];
let lesson,session,timers=[],audio=null,version=0,rewardTimer;
const shuffle=a=>{const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
const element=(tag,text,cls)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x};
const button=(text,fn,cls)=>{const b=element('button',text,cls);b.type='button';b.onclick=fn;return b};
function image(item){const p=element('img',undefined,'pic');p.src=item.image;p.alt='Flashcard de la leçon';return p}
function later(fn,ms){const id=setTimeout(fn,ms);timers.push(id);return id}
function stop(){version++;timers.forEach(clearTimeout);timers=[];if(audio){audio.pause();audio=null}window.speechSynthesis?.cancel()}
function speak(item){if(audio)audio.pause();window.speechSynthesis?.cancel();const text=typeof item==='string'?item:item.en;if(typeof item!=='string'&&item.audio){audio=new Audio(item.audio);audio.play().catch(()=>say(text));return}say(text)}
function say(text){if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){$('status').textContent='La voix anglaise n’est pas disponible sur cet appareil. Utilise « Afficher le mot » pour jouer avec une aide.';return}const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.82;u.voice=speechSynthesis.getVoices().find(v=>v.lang==='en-GB')||null;u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))$('status').textContent='Voix indisponible : utilise « Afficher le mot ».'};speechSynthesis.speak(u)}
const player=()=>($('nickname').value.trim()||'Loup bleu').slice(0,18);
function storageKey(){return 'zoumai-english-arcade-v1:'+lesson.id+':'+encodeURIComponent(player().toLowerCase())}
function saved(){try{return JSON.parse(localStorage.getItem(storageKey()))||{}}catch{return {}}}
function save(score){const state=saved();state[session.mode]=Math.max(state[session.mode]||0,score);try{localStorage.setItem(storageKey(),JSON.stringify(state));localStorage.setItem('zoumai-player-nickname',player())}catch{}}
function home(){stop();session=null;$('home').hidden=false;$('game').hidden=true;$('reward').hidden=true;menu()}
function menu(){const state=saved();$('menu').replaceChildren();modes.forEach((m,i)=>{const b=button('',()=>start(i),'mission');b.dataset.mode=i;b.append(element('span',m[0],'icon'),element('strong',lesson.id===1&&i===5?'Have you got…?':lesson.id===1&&i===6?'My School Bag':lesson.id===1&&i===7?'Classroom English':m[1]),element('small',m[2]));if(state[i]!==undefined)b.append(element('small','Record : '+state[i]+' / 100','best'));$('menu').append(b)});$('playerPoints').textContent='Scores conservés sur cet appareil';}
function start(mode,review){stop();$('home').hidden=true;$('game').hidden=false;session={mode,index:0,correct:0,mistakes:[],deck:shuffle(review||lesson.items),review:!!review,total:mode===3?Math.min(4,lesson.items.length):Math.min(8,(review||lesson.items).length)};render()}
function feedback(ok,text){$('feedback').className=ok?'good':'bad';$('feedback').textContent=text;if(ok){$('reward').hidden=false;clearTimeout(rewardTimer);rewardTimer=setTimeout(()=>$('reward').hidden=true,950)}}
function render(){stop();if(session.index>=session.total){finish();return}const token=version;session.done=false;session.assisted=false;session.item=session.deck[session.index%session.deck.length];session.kind=session.mode===9?[0,1,4,2,7,6,0,1][session.index%8]:session.mode;
 $('modeTitle').textContent=modes[session.mode][1];$('progress').textContent=(session.index+1)+' / '+session.total;$('points').textContent=Math.round(session.correct/session.total*100)+' / 100';$('work').replaceChildren();$('actions').replaceChildren();$('feedback').textContent='';$('feedback').className='';
 const kind=session.kind;if(kind===3){match();return}if(kind===2){memory(token);return}if(kind===5||(kind===6&&lesson.id===1)){bag(kind);return}if(kind===6){build(true);return}if(kind===4){build(false);return}if(kind===7){phrases();return}if(kind===0){heading('Listen & Find','Écoute, puis choisis la bonne image.');audioControls(session.item);choices(session.item,lesson.items,true);return}
 heading(kind===8?'Fast Challenge':'Image → Word','Choisis le mot qui correspond à l’image.');$('work').append(image(session.item));choices(session.item,lesson.items,false);if(kind===8){const clock=element('div','8','clock');$('work').prepend(clock);let seconds=8;function tick(){if(version!==token||session.done)return;clock.textContent=String(--seconds);if(seconds===0)complete(false,'Temps écoulé · '+session.item.en);else later(tick,1000)}later(tick,1000)}
}
function heading(title,hint){$('work').append(element('h2',title));if(hint)$('work').append(element('p',hint))}
function audioControls(item){$('work').append(button('🔊 Écouter',()=>speak(item),'audio'));const help=button('Afficher le mot (avec aide)',()=>{if(session.done)return;session.assisted=true;help.textContent=item.en;help.disabled=true});$('work').append(help)}
function choices(target,pool,pictures){const wrap=element('div',undefined,'choices');shuffle([target,...shuffle(pool.filter(x=>x.en!==target.en)).slice(0,3)]).forEach(item=>{const b=button(pictures?'':item.en,()=>{if(session.done)return;wrap.querySelectorAll('button').forEach(x=>{x.disabled=true;if(x.dataset.answer===target.en)x.classList.add('correct')});const ok=item.en===target.en;b.classList.add(ok?'correct':'wrong');complete(ok,ok?'Well done!':'Bonne réponse : '+target.en)});b.dataset.answer=item.en;if(pictures)b.append(image(item));wrap.append(b)});$('work').append(wrap)}
function complete(ok,text){if(session.done)return;session.done=true;stop();if(ok&&!session.assisted)session.correct++;else session.mistakes.push(session.item);feedback(ok,text+(session.assisted?' · avec aide':''));$('points').textContent=Math.round(session.correct/session.total*100)+' / 100';$('actions').append(button('🔊 Réécouter',()=>speak(session.item),'audio'),button('Continuer →',()=>{session.index++;render()}));}
function memory(token){const cards=shuffle(lesson.items).slice(0,Math.min(5,lesson.items.length));const gone=session.review?session.item:cards[Math.floor(Math.random()*cards.length)];if(!cards.includes(gone))cards[0]=gone;session.item=gone;heading('Look carefully!','Tu as cinq secondes pour mémoriser les images.');const board=element('div',undefined,'memory');const slots=cards.map(item=>{const slot=element('div',undefined,'slot');slot.append(image(item));board.append(slot);return slot});$('work').append(board);const clock=element('div','5','clock');$('work').append(clock);let remaining=5;function tick(){if(version!==token)return;clock.textContent=String(--remaining);if(remaining){later(tick,1000);return}clock.remove();$('work').querySelector('h2').textContent="What’s Missing?";$('work').querySelector('p').textContent='Quelle image a disparu ?';slots[cards.indexOf(gone)].replaceChildren(element('span','?'));choices(gone,lesson.items,false)}later(tick,1000)}
function match(){heading('Match','Choisis un son à gauche, puis son image à droite.');const pool=shuffle(lesson.items).slice(0,4),board=element('div',undefined,'match'),sounds=element('div'),pictures=element('div');let selected=null,matched=new Set();const soundButtons=new Map(),picButtons=new Map();pool.forEach((item,i)=>{const b=button('🔊 '+(i+1),()=>{if(matched.has(item.en))return;selected=item;soundButtons.forEach(x=>x.classList.remove('selected'));b.classList.add('selected');speak(item)},'audio');soundButtons.set(item.en,b);sounds.append(b)});shuffle(pool).forEach(item=>{const b=button('',()=>{if(!selected||matched.has(item.en))return;const target=selected;if(item.en===target.en){matched.add(item.en);soundButtons.get(item.en).disabled=true;b.disabled=true;selected=null;session.correct++;feedback(true,'Well done!');$('progress').textContent=matched.size+' / '+pool.length;$('points').textContent=Math.round(matched.size/pool.length*100)+' / 100';if(matched.size===pool.length){session.index=session.total;finish()}}else{if(!session.mistakes.some(x=>x.en===target.en))session.mistakes.push(target);feedback(false,'Réécoute le son et essaie une autre image.');speak(target)}});b.append(image(item));picButtons.set(item.en,b);pictures.append(b)});session.total=pool.length;board.append(sounds,pictures);$('work').append(board)}
function build(sentence){const item=sentence?lesson.phrases[session.index%lesson.phrases.length]:session.item;session.item=item;const tokens=sentence?item.en.split(/\s+/):Array.from(item.en);const selected=[];heading(sentence?'Build the sentence':'Spelling',sentence?item.fr:'Construis le mot anglais avec les lettres.');if(!sentence)$('work').append(image(item));$('work').append(button('🔊 Écouter',()=>speak(item),'audio'));const line=element('div','…','answer'),box=element('div',undefined,'tokens');const check=button('Vérifier',()=>{if(session.done||selected.length!==tokens.length)return;const answer=selected.map(x=>x.value).join(sentence?' ':'');if(answer===item.en){box.querySelectorAll('button').forEach(x=>x.disabled=true);check.disabled=true;complete(true,'Well done!')}else{session.assisted=true;feedback(false,'Pas encore. Retire des lettres ou des mots et recommence.');}});check.disabled=true;const update=()=>{line.textContent=selected.map(x=>x.value).join(sentence?' ':'')||'…';check.disabled=selected.length!==tokens.length};shuffle(tokens.map((value,id)=>({value,id}))).forEach(t=>{const b=button(t.value===' '?'␣':t.value,()=>{if(session.done)return;selected.push({value:t.value,button:b});b.disabled=true;update()});box.append(b)});$('work').append(line,box);const undo=()=>{if(session.done)return;const last=selected.pop();if(last)last.button.disabled=false;update()};$('actions').append(button('↶ Retirer',undo),button('Recommencer',()=>{if(session.done)return;while(selected.length)undo()}),check)}
function bag(kind){const pool=lesson.id===1?lesson.items.filter(x=>x.kind==='object'):lesson.items;const cards=shuffle(pool).slice(0,Math.min(3,pool.length-1));const present=session.index%2===0;const item=present?cards[0]:pool.find(x=>!cards.includes(x));session.item=item;heading(kind===5?(lesson.id===1?'Have you got ':'Can you see ')+item.en+'?':'My School Bag','Observe les cartes : l’objet est-il présent ?');const board=element('div',undefined,'memory');cards.forEach(x=>{const slot=element('div',undefined,'slot');slot.append(image(x));board.append(slot)});$('work').append(board);const yes=kind===5?(lesson.id===1?'Yes, I have.':'Yes, I can.'):'I have got '+item.en+'.',no=kind===5?(lesson.id===1?"No, I haven’t.":"No, I can’t."):'I haven’t got '+item.en+'.';const wrap=element('div',undefined,'choices');[yes,no].forEach((text,i)=>wrap.append(button(text,()=>{if(session.done)return;wrap.querySelectorAll('button').forEach(b=>b.disabled=true);complete((i===0)===present,((i===0)===present?'Well done!':'Bonne réponse : '+(present?yes:no)))})));$('work').append(wrap)}
function phrases(){const target=lesson.phrases[session.index%lesson.phrases.length];session.item=target;heading('English in action',target.fr);choices(target,lesson.phrases,false)}
function finish(){stop();const raw=session.correct-(session.mode===3?session.mistakes.length:0),score=Math.max(0,Math.round(raw/session.total*100));save(score);$('progress').textContent='Terminé';$('points').textContent=score+' / 100';$('work').replaceChildren(element('h2','Mission complete!'),element('p',score+' points sur 100'));$('actions').replaceChildren();$('feedback').textContent='';const mode=session.mode;const errors=[...new Map(session.mistakes.filter(x=>lesson.items.includes(x)).map(x=>[x.en,x])).values()];if(session.mistakes.length){$('work').append(element('p','À revoir : '+[...new Set(session.mistakes.map(x=>x.en))].join(' · ')));if(errors.length&&![3,6,7].includes(mode))$('actions').append(button('↻ Rejouer mes erreurs',()=>start(mode,errors)))}else feedback(true,'Perfect!');$('actions').append(button('Rejouer',()=>start(mode)),button('Choisir un autre jeu',home));if(window.ZoumaiScores){ZoumaiScores.save('anglais',score,100);const rank=element('div');$('work').append(rank);ZoumaiScores.render('anglais','Champion d’anglais',rank)}}
$('back').onclick=home;$('nickname').addEventListener('change',()=>{try{localStorage.setItem('zoumai-player-nickname',player())}catch{}if(lesson)home()});window.addEventListener('pagehide',stop);
fetch('arcade-data.json?v=20261007').then(r=>{if(!r.ok)throw Error('Chargement impossible');return r.json()}).then(data=>{const id=Number(new URLSearchParams(location.search).get('lesson')||1);lesson=data.find(x=>x.id===id);if(!lesson)throw Error('Cette leçon est introuvable');$('title').textContent=lesson.title;document.title=lesson.title+' · 10 jeux · Zou Maï';$('lessonArt').src=lesson.icon;$('comic').href='index.html#bd-'+lesson.id;if(lesson.legacy){$('legacy').hidden=false;$('legacy').href=lesson.legacy}try{$('nickname').value=localStorage.getItem('zoumai-player-nickname')||''}catch{}lesson.items.forEach(item=>{const b=button('',()=>speak(item));b.append(image(item),element('span',item.en));$('flashcards').append(b)});home()}).catch(e=>{$('status').textContent=e.message+'. Recharge la page pour réessayer.'});
